Vagrant.configure(2) do |config|

	config.vm.provider "virtualbox" do |v|
		v.cpus = 2
		v.memory = 1024
	end
	
	config.vm.box = "ubuntu/wily64"
	
	config.vm.network "private_network", ip: "192.168.0.10"
	
	config.vm.synced_folder ".", "/vagrant", disabled: true
	
	config.vm.provision "shell" do |shell|
		shell.path = "shell/setup.sh"
	end
end